// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:959471381015:web:e38239398b5a1b53488a52',
    messagingSenderId: '959471381015',
    projectId: 'reddit-project-f83a5',
    authDomain: 'reddit-project-f83a5.firebaseapp.com',
    storageBucket: 'reddit-project-f83a5.firebasestorage.app',
    measurementId: 'G-TGB7EEGB8R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:959471381015:android:853ea10ccd3e56fd488a52',
    messagingSenderId: '959471381015',
    projectId: 'reddit-project-f83a5',
    storageBucket: 'reddit-project-f83a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:959471381015:ios:02b0ce9edc4c9c94488a52',
    messagingSenderId: '959471381015',
    projectId: 'reddit-project-f83a5',
    storageBucket: 'reddit-project-f83a5.firebasestorage.app',
    iosBundleId: 'com.example.redditProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:959471381015:ios:02b0ce9edc4c9c94488a52',
    messagingSenderId: '959471381015',
    projectId: 'reddit-project-f83a5',
    storageBucket: 'reddit-project-f83a5.firebasestorage.app',
    iosBundleId: 'com.example.redditProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:959471381015:web:0e56d5b130dda529488a52',
    messagingSenderId: '959471381015',
    projectId: 'reddit-project-f83a5',
    authDomain: 'reddit-project-f83a5.firebaseapp.com',
    storageBucket: 'reddit-project-f83a5.firebasestorage.app',
    measurementId: 'G-Q1GKK7WMRB',
  );
}
